---
#####################
# Probe SSH Port(s) #
#####################
- name: "test ssh on port {{ modified_ssh_port | default('') }}"
  wait_for:
    port: "{{ modified_ssh_port | default('314') }}"
    state: 'started'
    timeout: "{{ wait_for_ssh_timeout | default('5') }}"
    host: "{{ ansible_host | default(inventory_hostname) }}"
  delegate_to: localhost
  register: custom_ssh
  ignore_errors: true
  when:
    - modified_ssh_port != ""

- name: test default ssh port
  wait_for:
    port: 22
    state: 'started'
    timeout: "{{ wait_for_ssh_timeout | default('5') }}"
    host: "{{ ansible_host | default(inventory_hostname) }}"
  delegate_to: localhost
  register: default_ssh
  ignore_errors: true

- name: "set ansible_ssh_port to {{ modified_ssh_port | default('') }}"
  set_fact:
    ansible_ssh_port: "{{ modified_ssh_port | default('') }}"
    ansible_port: "{{ modified_ssh_port | default('') }}"
  when:
    - custom_ssh is defined
    - modified_ssh_port != ""
    - custom_ssh.elapsed < wait_for_ssh_timeout

- name: set ansible_ssh_port to default
  set_fact:
    ansible_ssh_port: 22
    ansible_port: 22
  when:
    - default_ssh.elapsed < wait_for_ssh_timeout

###############################
# Pre-configure OS for Python #
###############################
- name: manually check OS version
  raw: "cat /etc/issue | awk '{ print $1,$3 }' | xargs echo -n"
  register: manual_os_version
  changed_when: false

- name: set bootstrap_python for localhost
  set_fact:
    bootstrap_python: true
  when:
    - manual_os_version.stdout in os_without_python_preinstalled
  delegate_to: localhost
  tags:
    - bootstrap-python

- name: install python
  raw: "apt update -y && apt install python3 -y"
  changed_when: false
  when:
    - bootstrap_python | bool
    - manual_os_version.stdout | regex_search('Debian')
    - manual_os_version.stdout in os_without_python_preinstalled
  tags:
    - bootstrap-python

- name: set default python
  raw: "update-alternatives --install /usr/bin/python python /usr/bin/python3 1"
  changed_when: false
  when:
    - bootstrap_python | bool

- name: override default python version
  set_fact:
    ansible_python_interpreter: "{{ remote_python }}"
  when: manual_os_version.stdout in os_without_python_preinstalled

#######################
# Test SSH Connection #
#######################
- name: try to ansible ping the host before moving on
  ping:

####################
# Install SSH Keys #
####################
- name: install ssh key(s)
  authorized_key:
    user: "{{ ssh_key_user | default(item.user) }}"
    state: present
    key: "{{ item.key }}"
  become: "{{ ssh_key_sudo | default(false) }}"
  with_items:
    - "{{ ssh_keys | default([]) }}"
  when:
    - configure_ssh_keys | bool
